### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by ocramsevla** [samsmu/JIRA2PM#18]
Hi BlackCatter,

It's possible to help me with the configuration of  custom fields?

I have two custom fields that I would like to add in my google sheet table (customfield_10105 and customfield_10104), but I can't find a way to do this.

I have the setup done, but I don't see any options fields or a group called Custom Fields to add any custom field by writing it's name in JIRA.

Can you help me on this configuration?

![image](https://user-images.githubusercontent.com/32346247/30943075-9bdd5248-a3e6-11e7-83aa-e67acaa38974.png)

**Comment by ocramsevla** [comment]
Hi, @BlackCatter, can you help me on this matter?

**Comment by BlackCatter** [comment]
Hi @ocramsevla , sorry for the late reply, was away last week and overlooked this message

Have you tried pressing "Reload Custom Fields" button? It should add all custom fields in your Jira to the list where you can select which one you want to show and ,if you want, regex to format value (leave regex field blank if you don't need it)

Usually <code>customfield_</code> is a inside Jira's naming scheme for fields, the name of the field will be the same as you see it in Jira

**Comment by ocramsevla** [comment]
Hi @BlackCatter, thanks for your reply.

About your question, yes I already tried pressing the "Reload Custom Fields" button but nothing happen!

We have more then 100 custom fiels. Is it because of this?

**Comment by BlackCatter** [comment]
Can you please check console log for errors when you are pressing button? 
For Google Chrome it is <code>Ctrl + Shift + i</code> and then switch to Console tab

I'll try tomorrow scenario with more then 100 custom fields to see if this is an issue for this behavior

**Comment by ocramsevla** [comment]
Hi again, 
I send you the console screenshot with all logs.

Please, if you have any doubt I'm full available.

![image](https://user-images.githubusercontent.com/32346247/31284793-7fa18b22-aab1-11e7-9919-f30054445b39.png)

**Comment by BlackCatter** [comment]
Hi! 

I've fixed error <code>Uncaught ReferenceError: stopProgressBar is not defined</code> which was preventing displaying error message. Can you try again updating custom fields? There is now should be a red text bellow all fields lists, explaining what error is.

**Comment by ocramsevla** [comment]
Hi!
error message: ScriptError: Argument too large: value

![image](https://user-images.githubusercontent.com/32346247/31306613-89670296-ab4b-11e7-9c8f-4a3c702c6fdb.png)

**Comment by BlackCatter** [comment]
I see, you were right, error is cause of custom fields amount. Data for custom fields is larger than allowed data size for single user property. 

Will fix it asap

**Comment by ocramsevla** [comment]
Many thanks for your help. I will wait your feedback!

**Comment by BlackCatter** [comment]
Have updated script to support very large amount of custom fields. Can you try it out and confirm that it has fixed the issue?

**Comment by ocramsevla** [comment]
Hi @BlackCatter!
Now I can see all the custom fields. amazing!!! Many thanks for your support!

![image](https://user-images.githubusercontent.com/32346247/31310394-67326870-ab8f-11e7-9a71-407f174245d3.png)

**Comment by BlackCatter** [comment]
You are welcome! :grinning:

**Comment by ocramsevla** [comment]
Hi @BlackCatter  I have one more question. 
on the "Fields to Show" I can't find the "project" field.
It's possibel add this field?

**Comment by BlackCatter** [comment]
Sure, will add it tomorrow :D

**Comment by BlackCatter** [comment]
Have added :smirk_cat:

**Comment by ocramsevla** [comment]
thanks!!!
