### ISSUE TITLE
like your approach

### ISSUE THREAD

**Issue by ljay79** [samsmu/JIRA2PM#21]
Hi guys, just came across your add-on while i was updating my release [Jira Sheet Tool](https://github.com/ljay79/jira-tools).

I like your sidebar approach and the more techi way of providing JQL editor for the more advanced users.

Maybe you guys are interested of joining forces and do 1 awesome add-on rather than 2 (just) good ones? :)

**Comment by BlackCatter** [comment]
Hi @ljay79 !

This is an interesting propositions, but at the moment we don't have time to curate merging our add-ons
