### ISSUE TITLE
Not Recognizing New Custom Fields

### ISSUE THREAD

**Issue by ebiss** [samsmu/JIRA2PM#22]
Hey, it's me again :)
LOVING the add-on thus far! I needed to add another custom field to my JIRA instance, but I don't see it showing up as a new option for one of the columns. How can I refresh the list of available custom fields in the add-on? I tried removing the add-on and re-adding it, no luck there.

**Comment by BlackCatter** [comment]
Hi!

There is a <code>Reload Custom Fields</code> button at the end of Custom Fields group
![image](https://user-images.githubusercontent.com/10657551/31968388-018068f6-b922-11e7-8dcb-f2cfdf1d99ee.png)

**Comment by ebiss** [comment]
Worked like a dream, thanks for the super fast response!
