### ISSUE TITLE
Custom field of type multiple versions shows as Object

### ISSUE THREAD

**Issue by mselvan** [samsmu/JIRA2PM#23]
Hello,

We have a custom field of type multiple versions (Advanced). When pulling that field, we get "[object Object]" instead of the actual value.

**Comment by BlackCatter** [comment]
Hi! Thanks for reporting this issue.

Should be fixed by now, can you check and confirm?

**Comment by mselvan** [comment]
Ah this is crazy :-) Thanks for the fix.

Besides @AureanAsaf says hi :-)

**Comment by AureanAsaf** [comment]
Told you @mselvan , these guys are the best!! :)
