### ISSUE TITLE
Connection does not work with same credentials

### ISSUE THREAD

**Issue by nchcap** [samsmu/JIRA2PM#53]
Hi,

I am getting connection error while using the same credentials as usual.

Maybe it is related to this mail I received from Atlassian a while ago :

> At Atlassian, we take your security seriously. That's why   we've introduced support for API tokens on all Atlassian Cloud sites,   replacing Atlassian account passwords for all Jira and Confluence APIs.
--
This means you may need to take action.
By 3rd June 2019,             if you're using a REST endpoint in Jira or Confluence Cloud with             basic authentication, you will need to have updated your app or integration             to use an API token, OAuth, or Atlassian Connect. | By 3rd June 2019,             if you're using a REST endpoint in Jira or Confluence Cloud with             basic authentication, you will need to have updated your app or integration             to use an API token, OAuth, or Atlassian Connect.

Do you think basic authentification still works with your plugin (which is awesome btw) ?

Thanks

Nicolas

**Comment by BlackCatter** [comment]
Hi!

Thanks for making an issue, I haven't got such email and can now see that I am not connecting to cloud Jira instance.

I'll update plugin with OAuth or Atlassian Connect authentication this weekend :smile_cat:

**Comment by nchcap** [comment]
@BlackCatter Thank you so much !

**Comment by Black-Cat** [comment]
@nchcap I've added some small changes to make clear how to connect to jira cloud now. But changes need to be reviewed by Google and will be published maybe in a week. I'll close issue when they'll get public.

As for connection to cloud Jira, you can use current version of add-on. Instead of username use your email, and instead of password use [API token](https://confluence.atlassian.com/cloud/api-tokens-938839638.html)

**Comment by nchcap** [comment]
@BlackCatter I've tested the connection with the API Token, it works perfectly :) thank you very much !

**Comment by Black-Cat** [comment]
Thank you for testing and using add-on!
