### ISSUE TITLE
Error 400 when fetching issues

### ISSUE THREAD

**Issue by NahtreX** [samsmu/JIRA2PM#55]
Error 400 is displayed whenever fetching issues from JIRA.

For further information I'm logged in with a JIRA API Token, and the fields I am displaying are Key (as a link), Summary, Project, Priority, Status, Asignee, Reporter and Created.

The issues are not fetched and the api gets stuck.

**Comment by Black-Cat** [comment]
Hi! Thanks for reporting this issue. Can't reproduce but i'll take a deeper look this weekend

**Comment by NahtreX** [comment]
Let me know if you need anything from my end.

**Comment by NahtreX** [comment]
Hey, so, quick update on this.

I found that if you try to fetch a list of issues with no JQL query the api actually makes the table index but doesn't fill it (obvious reasons) and the error 400 does not show, it shows the corresponding error for an empty JQL query field.

I feel like the error is in how the API fetches the issues, did some digging and found out that JIRA shows this error when you push or pull strings without double quotation marks, as in, the ones used to make it a string and ones inside the string (e.g. "\"STRING\"")... Not sure if that's the case.

**Comment by NahtreX** [comment]
Turns out this issue happens only when I use my account and with any other account while using the username instead the e-mail. Otherwise it's working.
