### ISSUE TITLE
Storage issue

### ISSUE THREAD

**Issue by NahtreX** [samsmu/JIRA2PM#56]
Hey! I realized you maybe are not working on this project anymore since it no longer appears on the google marketstore, but I am having an issue and I hoped you could point me in the right direction.

I am getting the following error when fetching settings, I believe since the storage is no longer working:
ScriptError: Exception: Data storage error

If a server change is needed could you point me to where in the code to make said change so I can provide it with my own server?

Many thanks.

**Comment by Black-Cat** [comment]
Hi @NahtreX !

Yes, sadly project is not being developed. It was really time consuming to go through google's review procedure every single update.

Sorry, but I don't have idea about error at first glance, too generic. Code doesn't use any external storage, all data is stored in user's data storage for addon accessed by `PropertiesService.getUserProperties()`. I'll try to poke code randomly at weekends and will send message (or even patch) if found anything.

There is also now an official jira - google spreadsheets integration, but i haven't used it yet. It may be more complete and have more features.

**Comment by NahtreX** [comment]
Thanks for the help.

Yor comment ended up pointing me to this https://issuetracker.google.com/issues/36765657

So maybe the error is not even on the code

**Comment by Black-Cat** [comment]
Ah, thanks for the link ^_^ Let's wait till it's resolved and then i'll close this issue

**Comment by Black-Cat** [comment]
Seems to be fixed. Will reopen if it's still happening
